[2024-01-05T18:10:48.683+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T18:10:48.688+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T18:10:48.688+0000] {taskinstance.py:2171} INFO - Starting attempt 5 of 5
[2024-01-05T18:10:48.694+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T18:10:48.697+0000] {standard_task_runner.py:60} INFO - Started process 563 to run task
[2024-01-05T18:10:48.699+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmprf668ho6']
[2024-01-05T18:10:48.700+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask send_metadata_to_kafka
[2024-01-05T18:10:48.726+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host d23442f9ddc6
[2024-01-05T18:10:48.764+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dummy_dag' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T18:10:48.768+0000] {logging_mixin.py:188} INFO - Erro ao chamar o endpoint Flask: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /send_metadata (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8e63f580>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-01-05T18:10:48.768+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-05T18:10:48.773+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dummy_dag, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T181048, end_date=20240105T181048
[2024-01-05T18:10:48.795+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T18:10:48.806+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
