[2024-01-05T17:36:10.450+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T17:36:10.455+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T17:36:10.456+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-05T17:36:10.462+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T17:36:10.465+0000] {standard_task_runner.py:60} INFO - Started process 113 to run task
[2024-01-05T17:36:10.467+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmpr2zmkuf8']
[2024-01-05T17:36:10.468+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask send_metadata_to_kafka
[2024-01-05T17:36:10.494+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_dag.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host d9447f6fb5a6
[2024-01-05T17:36:10.530+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dummy_dag' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T17:40:57.726+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-01-05T17:40:57.730+0000] {process_utils.py:131} INFO - Sending 15 to group 113. PIDs of all processes in the group: [113]
[2024-01-05T17:40:57.731+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 113
[2024-01-05T17:41:10.795+0000] {taskinstance.py:2451} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-01-05T17:41:10.842+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=113, status='terminated', exitcode=0, started='17:36:10') (113) terminated with exit code 0
