[2024-01-06T01:20:10.413+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_dag.kafka_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-06T01:20:10.418+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_dag.kafka_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-06T01:20:10.418+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-06T01:20:10.424+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): kafka_task> on 2024-01-01 00:00:00+00:00
[2024-01-06T01:20:10.427+0000] {standard_task_runner.py:60} INFO - Started process 1201 to run task
[2024-01-06T01:20:10.430+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'kafka_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmp3ufd6ll7']
[2024-01-06T01:20:10.430+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask kafka_task
[2024-01-06T01:20:10.455+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_dag.kafka_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host bb6e3efe9410
[2024-01-06T01:20:10.492+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dummy_dag' AIRFLOW_CTX_TASK_ID='kafka_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-06T01:20:10.495+0000] {dummy_dag.py:26} ERROR - Erro ao chamar o endpoint Flask: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /send_metadata (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9e31f850>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-01-06T01:20:10.495+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-06T01:20:10.500+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dummy_dag, task_id=kafka_task, execution_date=20240101T000000, start_date=20240106T012010, end_date=20240106T012010
[2024-01-06T01:20:10.522+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-06T01:20:10.534+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
