[2024-01-06T01:20:09.345+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummy_dag.cassandra_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-06T01:20:09.349+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummy_dag.cassandra_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-06T01:20:09.350+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-06T01:20:09.356+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): cassandra_task> on 2024-01-01 00:00:00+00:00
[2024-01-06T01:20:09.359+0000] {standard_task_runner.py:60} INFO - Started process 1199 to run task
[2024-01-06T01:20:09.361+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dummy_dag', 'cassandra_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmpicec4rko']
[2024-01-06T01:20:09.362+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask cassandra_task
[2024-01-06T01:20:09.386+0000] {task_command.py:423} INFO - Running <TaskInstance: dummy_dag.cassandra_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host bb6e3efe9410
[2024-01-06T01:20:09.422+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='dummy_dag' AIRFLOW_CTX_TASK_ID='cassandra_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-06T01:20:09.428+0000] {dummy_dag.py:38} ERROR - Erro ao chamar o endpoint Kafka: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /consume_and_insert (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9e31f850>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-01-06T01:20:09.428+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-06T01:20:09.433+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dummy_dag, task_id=cassandra_task, execution_date=20240101T000000, start_date=20240106T012009, end_date=20240106T012009
[2024-01-06T01:20:09.453+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-06T01:20:09.468+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
