[2024-01-05T16:04:48.706+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T16:04:48.711+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T16:04:48.711+0000] {taskinstance.py:2171} INFO - Starting attempt 14 of 14
[2024-01-05T16:04:48.719+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T16:04:48.722+0000] {standard_task_runner.py:60} INFO - Started process 83 to run task
[2024-01-05T16:04:48.724+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_metadata_collector', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag_metadata_collector.py', '--cfg-path', '/tmp/tmp0fpgnnb3']
[2024-01-05T16:04:48.725+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask send_metadata_to_kafka
[2024-01-05T16:04:48.753+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host 73232b21783f
[2024-01-05T16:04:48.796+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_metadata_collector' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T16:04:48.796+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_metadata_collector.py", line 23, in send_metadata_to_kafka
    'bootstrap.servers': bootstrap_servers,
NameError: name 'bootstrap_servers' is not defined
[2024-01-05T16:04:48.802+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_metadata_collector, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T160448, end_date=20240105T160448
[2024-01-05T16:04:48.810+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task send_metadata_to_kafka (name 'bootstrap_servers' is not defined; 83)
[2024-01-05T16:04:48.822+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-05T16:04:48.833+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
