[2024-01-05T15:55:54.636+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T15:55:54.641+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T15:55:54.641+0000] {taskinstance.py:2171} INFO - Starting attempt 12 of 12
[2024-01-05T15:55:54.647+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T15:55:54.650+0000] {standard_task_runner.py:60} INFO - Started process 288 to run task
[2024-01-05T15:55:54.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_metadata_collector', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dag_metadata_collector.py', '--cfg-path', '/tmp/tmp0zxjt45y']
[2024-01-05T15:55:54.653+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask send_metadata_to_kafka
[2024-01-05T15:55:54.677+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host 890a10b6f2f9
[2024-01-05T15:55:54.713+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_metadata_collector' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T15:55:54.733+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-01-05T15:55:54.733+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-01-05T15:55:54.734+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-01-05T15:55:54.734+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-01-05T15:55:54.782+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2024-01-05T15:55:54.783+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2024-01-05T15:55:54.783+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-01-05T15:55:54.832+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2024-01-05T15:55:54.832+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]> returned error 99. Disconnecting.
[2024-01-05T15:55:54.833+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 99 EADDRNOTAVAIL
[2024-01-05T15:55:54.833+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_metadata_collector.py", line 13, in send_metadata_to_kafka
    producer = KafkaProducer(bootstrap_servers=["localhost:9092"],
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-01-05T15:55:54.839+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_metadata_collector, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T155554, end_date=20240105T155554
[2024-01-05T15:55:54.845+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task send_metadata_to_kafka (NoBrokersAvailable; 288)
[2024-01-05T15:55:54.865+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-05T15:55:54.875+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
