[2024-01-05T15:55:23.304+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T15:55:23.309+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T15:55:23.309+0000] {taskinstance.py:2171} INFO - Starting attempt 11 of 11
[2024-01-05T15:55:23.316+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T15:55:23.319+0000] {standard_task_runner.py:60} INFO - Started process 278 to run task
[2024-01-05T15:55:23.321+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_metadata_collector', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_metadata_collector.py', '--cfg-path', '/tmp/tmp76_5hoxi']
[2024-01-05T15:55:23.322+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask send_metadata_to_kafka
[2024-01-05T15:55:23.349+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host 890a10b6f2f9
[2024-01-05T15:55:23.387+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_metadata_collector' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T15:55:23.409+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-01-05T15:55:23.409+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-01-05T15:55:23.410+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-01-05T15:55:23.412+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-01-05T15:55:23.412+0000] {conn.py:315} ERROR - DNS lookup failed for broker:9092 (0)
[2024-01-05T15:55:23.412+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_metadata_collector.py", line 13, in send_metadata_to_kafka
    producer = KafkaProducer(bootstrap_servers=["broker:9092"],
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-01-05T15:55:23.418+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_metadata_collector, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T155523, end_date=20240105T155523
[2024-01-05T15:55:23.424+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task send_metadata_to_kafka (NoBrokersAvailable; 278)
[2024-01-05T15:55:23.454+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-05T15:55:23.463+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
