[2024-01-05T15:03:18.279+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T15:03:18.284+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-05T15:03:18.285+0000] {taskinstance.py:2171} INFO - Starting attempt 7 of 7
[2024-01-05T15:03:18.291+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_metadata_to_kafka> on 2024-01-01 00:00:00+00:00
[2024-01-05T15:03:18.294+0000] {standard_task_runner.py:60} INFO - Started process 174 to run task
[2024-01-05T15:03:18.296+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_metadata_collector', 'send_metadata_to_kafka', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag_metadata_collector.py', '--cfg-path', '/tmp/tmpom2hwrxg']
[2024-01-05T15:03:18.297+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask send_metadata_to_kafka
[2024-01-05T15:03:18.322+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_metadata_collector.send_metadata_to_kafka scheduled__2024-01-01T00:00:00+00:00 [running]> on host f28a3bc17e9c
[2024-01-05T15:03:18.359+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_metadata_collector' AIRFLOW_CTX_TASK_ID='send_metadata_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-05T15:03:18.359+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_metadata_collector.py", line 11, in send_metadata_to_kafka
    producer = KafkaProducer(bootstrap_servers=["broker:29092"],
NameError: name 'KafkaProducer' is not defined
[2024-01-05T15:03:18.365+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_metadata_collector, task_id=send_metadata_to_kafka, execution_date=20240101T000000, start_date=20240105T150318, end_date=20240105T150318
[2024-01-05T15:03:18.370+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task send_metadata_to_kafka (name 'KafkaProducer' is not defined; 174)
[2024-01-05T15:03:18.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-05T15:03:18.399+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
